games = {
    # Main series (1–4)
    'JD1': 'Just Dance 1',
    'JD2': 'Just Dance 2',
    'JD3': 'Just Dance 3',
    'JD4': 'Just Dance 4',

    # Yearly titles (2014–2026)
    'JD2014': 'Just Dance 2014',
    'JD2015': 'Just Dance 2015',
    'JD2015C': 'Just Dance 2015 China',
    'JD2016': 'Just Dance 2016',
    'JD2017': 'Just Dance 2017',
    'JD2017C': 'Just Dance 2017 China',
    'JD2018': 'Just Dance 2018',
    'JD2019': 'Just Dance 2019',
    'JD2020': 'Just Dance 2020',
    'JDC': 'Just Dance 2020 China',
    'JD2021': 'Just Dance 2021',
    'JD2022': 'Just Dance 2022',
    'JD2023E': 'Just Dance 2023 Edition',
    'JD2024E': 'Just Dance 2024 Edition',
    'JD2025E': 'Just Dance 2025 Edition',
    'JD2026E': 'Just Dance 2026 Edition',

    # Other titles (approx. by release)
    'JD+': 'Just Dance PLUS',
    'DoB': 'Dance on Broadway',
    'Kids': 'Just Dance Kids',
    'Kids2': 'Just Dance Kids 2',
    'K2014': 'Just Dance Kids 2014',
    'Disney': 'Just Dance Disney Party',
    'Disney2': 'Just Dance Disney Party 2',
    'ABBA': 'ABBA: You Can Dance',
    'MJ:TE': 'Michael Jackson: The Experience',
    'Smurf': 'The Smurfs Dance Party',
    'JDGH': 'Just Dance: Greatest Hits',
    'JDSP': 'Just Dance: Summer Party / Extra Songs',
    'JDWii': 'Just Dance Wii',
    'JDWii2': 'Just Dance Wii 2',
    'JDWiiU': 'Just Dance Wii U',
    'TBEPE': 'The Black Eyed Peas Experience',
    'YoKai': 'Yo-kai Watch Dance',
    'JDU': 'Just Dance Unlimited',
    'JDUC/UC': 'Just Dance Unlimited (China)',
    'JDVS/VS': 'Just Dance Vitality School',
    'JDBO': 'Just Dance: Best Off',
    'JDN': 'Just Dance Now',
    'JDP': 'Just Dance Party',
    'VR': 'Just Dance VR'
}